const roles = {
  // --- base ---
  citizen: { faName: "شهروند ساده", teamFa: "شهر", hintFa: "بدون قابلیت", descFa: "قابلیت شب ندارید. روزها با صحبت، استدلال و رأی درست به پیدا شدن مافیا کمک کنید." },
  mafia: { faName: "مافیا ساده", teamFa: "مافیا", hintFa: "بدون قابلیت", descFa: "قابلیت مستقل ندارید. شب‌ها با مافیا مشورت می‌کنید و روزها تلاش می‌کنید شهر را گمراه کنید." },

  // --- classic / general ---
  mafiaBoss: { faName: "رئیس مافیا", teamFa: "مافیا", hintFa: "رهبر + شلیک", descFa: "رهبر تیم مافیاست؛ تصمیم نهاییِ شلیک شب با اوست. استعلام او برای کارآگاه همیشه «منفی» (شهروند) است." },
  godfather: { faName: "پدرخوانده", teamFa: "مافیا", hintFa: "رهبر + شلیک", descFa: "رهبر مافیاست و شلیک شب را تعیین می‌کند. استعلام او برای کارآگاه همیشه «منفی» (شهروند) است." },
  swindler: { faName: "شیاد", teamFa: "مافیا", hintFa: "برهم‌زنِ استعلام", descFa: "هر شب یک نفر را «می‌زند». اگر کارآگاه را هدف قرار دهد، استعلام کارآگاه همان شب «منفی» (شهروند) می‌شود — صرف‌نظر از هویت واقعیِ هدف استعلام. شیاد با تیم مافیا آشناست ولی مستقل بیدار می‌شود." },
  nato: { faName: "ناتو", teamFa: "مافیا", hintFa: "حدسِ نقش", descFa: "یک‌بار در طول بازی می‌تواند نقش دقیقِ یک بازیکن را حدس بزند؛ در صورت حدسِ درست آن بازیکن در هر شرایطی از بازی خارج می‌شود. در شب ناتو معمولاً شلیک انجام نمی‌شود." },
  negotiator: { faName: "مذاکره‌کننده", teamFa: "مافیا", hintFa: "مذاکره/تبدیل", descFa: "اگر ۱ یا ۲ نفر از مافیا حذف شده باشند، می‌تواند «شب مذاکره» را فعال کند. در شب مذاکره مافیا شلیک نمی‌کند؛ مذاکره‌کننده یک نفر را انتخاب می‌کند — اگر شهروند ساده یا زره‌پوشِ زره‌دار باشد، به مافیا تبدیل می‌شود؛ در غیر این صورت مذاکره شکست می‌خورد." },
  natasha: { faName: "ناتاشا", teamFa: "مافیا", hintFa: "سایلنتِ شب", descFa: "هر شب یک نفر را انتخاب می‌کند تا روز بعد نتواند صحبت کند (سایلنت). نمی‌تواند دو شب پشت‌سرهم یک نفر را سایلنت کند." },
  doctorLecter: { faName: "دکتر لکتر", teamFa: "مافیا", hintFa: "سیوِ مافیا", descFa: "پزشکِ تیم مافیاست. هر شب می‌تواند یک نفر را از شلیک نجات دهد. جان خودش را فقط یک‌بار در کل بازی می‌تواند نجات دهد." },
  jokerMafia: { faName: "جوکر مافیا", teamFa: "مافیا", hintFa: "برعکس‌کردن استعلام", descFa: "فقط ۲ بار در کل بازی می‌تواند یک نفر را انتخاب کند تا استعلام همان شب برای کارآگاه برعکس شود. انتخاب تکراری پشت‌سرهم (دو شب متوالی یک نفر) ممنوع است." },
  matador: { faName: "ماتادور", teamFa: "مافیا", hintFa: "گرفتنِ قابلیت", descFa: "هر شب با تیم مافیا بیدار می‌شود و یک نفر را نشان می‌دهد؛ آن نفر ۲۴ ساعت قابلیت ندارد. نمی‌تواند دو شب متوالی یک نفر را انتخاب کند." },
  saulGoodman: { faName: "ساول گودمن", teamFa: "مافیا", hintFa: "خرید/سوداگری", descFa: "یک‌بار در کل بازی می‌تواند یک «شهروند ساده» را بخرد و به «مافیا ساده» تبدیل کند. در شبِ خرید، گرداننده اعلام می‌کند که خرید انجام خواهد شد." },

  detective: { faName: "کارآگاه", teamFa: "شهر", hintFa: "استعلامِ شب", descFa: "هر شب می‌تواند یک نفر را استعلام کند؛ گرداننده با علامت مشخص می‌کند که آن نفر مافیاست یا شهروند. رئیس مافیا و پدرخوانده همیشه «منفی» (شهروند) نمایش می‌دهند." },
  investigator: { faName: "بازپرس", teamFa: "شهر", hintFa: "بازپرسی", descFa: "یک‌بار در کل بازی می‌تواند بازپرسی انجام دهد: دو نفر را همزمان به دفاعیه می‌آورد، آن دو کوتاه صحبت می‌کنند، سپس رأی‌گیری فقط بین همان دو نفر انجام می‌شود." },
  doctor: { faName: "پزشک", teamFa: "شهر", hintFa: "سیوِ شب", descFa: "هر شب می‌تواند جان یک نفر را از شلیک نجات دهد. نمی‌تواند دو شب پشت‌سرهم یک نفر را نجات دهد. نجات خودش فقط یک‌بار در کل بازی مجاز است." },
  watson: { faName: "دکتر واتسون", teamFa: "شهر", hintFa: "نجات", descFa: "مثل پزشک عمل می‌کند: هر شب جان یک نفر را نجات می‌دهد. نجات خودش فقط یک‌بار در کل بازی مجاز است." },
  researcher: { faName: "محقق", teamFa: "شهر", hintFa: "گره/پیوند", descFa: "به‌جز شب معارفه، هر شب می‌تواند خودش را به یک نفر «گره» بزند. اگر محقق با شات شب یا رأی از بازی خارج شود، فردِ گره‌خورده هم خارج می‌شود — معمولاً اگر رئیس مافیا را انتخاب کرده باشد، رئیس خارج نمی‌شود." },
  invulnerable: { faName: "رویین‌تن", teamFa: "شهر", hintFa: "زرهِ شب", descFa: "شلیک شبانه مافیا کشنده نیست. فقط از طریق رأی‌گیری روز یا شرایط خاص از بازی خارج می‌شود." },
  armored: { faName: "زره‌پوش", teamFa: "شهر", hintFa: "زره + بازگشت", descFa: "شلیک شبانه مافیا کشنده نیست. اگر با رأی‌گیری روز از بازی خارج شود، نقشش اعلام می‌شود و به بازی برمی‌گردد — از آن به بعد دیگر قابل مذاکره نیست." },
  sniper: { faName: "تک‌تیرانداز", teamFa: "شهر", hintFa: "شلیکِ محدود", descFa: "فقط یک‌بار در کل بازی می‌تواند شلیک کند. اگر به شهروند شلیک کند، خودش از بازی خارج می‌شود — حتی اگر پزشک نجات دهد." },
  professional: { faName: "حرفه‌ای", teamFa: "شهر", hintFa: "شلیک", descFa: "شب‌ها می‌تواند به کسی که مطمئن است مافیاست شلیک کند. اگر اشتباه به شهروند شلیک کند، خودش از بازی خارج می‌شود." },
  reporter: { faName: "خبرنگار", teamFa: "شهر", hintFa: "استعلامِ مذاکره", descFa: "در سناریو مذاکره، در شبی که مذاکره انجام می‌شود بیدار می‌شود و از گرداننده می‌فهمد آیا هدف مذاکره شهروند/زره‌پوش بود یا نه." },
  representative: { faName: "نماینده", teamFa: "شهر", hintFa: "قدرتِ روز", descFa: "یک‌بار در کل بازی می‌تواند یکی از دو قدرت روز را اعمال کند: وتوی رأی‌گیری (نتیجه رأی جاری را ملغی کند) یا حمایت از بازیکن (مصونیت موقت از حذف برای یک نفر در همان روز). شب بیدار می‌شود ولی اکشنی ثبت نمی‌شود." },
  hardJohn: { faName: "جان‌سخت", teamFa: "شهر", hintFa: "جان اضافه + استعلام", descFa: "اولین شلیک مافیا کشنده نیست (معمولاً خودش هم متوجه نمی‌شود). دو بار در کل بازی می‌تواند از گرداننده ساید یک بازیکنِ اخراج‌شده را بپرسد." },
  psychologist: { faName: "روانپزشک", teamFa: "شهر", hintFa: "قطع مکالمه", descFa: "دو بار در طول بازی می‌تواند توانایی صحبت یک بازیکن را برای آن جلسه از او بگیرد." },
  mayor: { faName: "شهردار", teamFa: "شهر", hintFa: "وتو/خروج", descFa: "یک‌بار در کل بازی (وقتی حداقل ۲ نفر در دفاعیه باشند و خودش در دفاعیه نباشد) می‌تواند رأی‌گیری را لغو کند یا حکم خروج مستقیم یکی از افراد دفاعیه را بدهد." },
  seller: { faName: "فروشنده", teamFa: "شهر", hintFa: "گرفتن قابلیت", descFa: "یک‌بار در کل بازی توانایی یک نفر را برای بقیه بازی از او می‌گیرد. فردای همان روز، انتخاب فروشنده توسط گرداننده اعلام می‌شود." },
  priest: { faName: "کشیش", teamFa: "شهر", hintFa: "حمایتِ گفت‌وگو", descFa: "شب‌ها چند نفر را انتخاب می‌کند تا روز بعد وقت صحبت اضافه داشته باشند. همچنین می‌تواند سایلنت ناتاشا را خنثی کند." },
  judge: { faName: "قاضی", teamFa: "شهر", hintFa: "تغییر رأی", descFa: "یک‌بار در کل بازی می‌تواند نتیجه رأی‌گیری روز را ملغی کند. معمولاً این تصمیم را شب اعلام می‌کند و اثرش فردا اعمال می‌شود." },
  commander: { faName: "فرمانده", teamFa: "شهر", hintFa: "تأیید شلیک", descFa: "بعد از اینکه تک‌تیرانداز هدف را انتخاب کرد، فرمانده بیدار می‌شود و می‌تواند شلیک را تأیید یا رد کند. اگر رد کند، تیر اصابت نمی‌کند." },

  // --- Capo (کاپو/دن) ---
  danMafia: { faName: "دن مافیا", teamFa: "مافیا", hintFa: "رئیس + پادزهر", descFa: "رئیس تیم مافیاست؛ استعلام او «منفی» (شهروند) است. یک پادزهر دارد (در برابر زهر عطار). می‌تواند قابلیت سوداگری داشته باشد (طبق سناریو کاپو)." },
  witch: { faName: "جادوگر", teamFa: "مافیا", hintFa: "کپیِ قابلیت", descFa: "هر شب یک شهروند را انتخاب می‌کند؛ اگر آن شهروند توانایی داشته باشد، توانایی‌اش روی جادوگر اجرا می‌شود (مثلاً: انتخاب کارآگاه = جادوگر استعلام می‌گیرد؛ انتخاب عطار = جادوگر زهر می‌زند)." },
  executioner: { faName: "جلاد", teamFa: "مافیا", hintFa: "حدسِ نقش", descFa: "مشابه ناتو: اگر نقش دقیق یک بازیکن را درست حدس بزند، آن بازیکن در هر شرایطی از بازی خارج می‌شود." },
  informant: { faName: "خبرچین", teamFa: "مافیا", hintFa: "جاسوس", descFa: "جاسوس تیم مافیاست؛ استعلام او «منفی» (شهروند) است. اگر کدخدا او را بیدار کند، مثل شهروند واکنش نشان می‌دهد و کدخدا لو نمی‌رود." },
  kadkhoda: { faName: "کدخدا", teamFa: "شهر", hintFa: "لینکِ شهر", descFa: "دو بار در کل بازی می‌تواند یک نفر را «لینک» کند: آن نفر بیدار می‌شود (بدون دانستن نقش) تا کدخدا بشناسدش. اگر فردِ لینک‌شده شهروند یا خبرچین باشد — بی‌خطر؛ اگر مافیا (غیر از خبرچین) باشد — کدخدا از بازی خارج می‌شود." },
  heir: { faName: "وارث", teamFa: "شهر", hintFa: "ارثِ نقش", descFa: "شب معارفه یک نفر را برای وراثت انتخاب می‌کند. تا قبل از اینکه آن نفر از بازی خارج شود، وارث نامیراست (مافیا نمی‌تواند او را شات کند). وقتی آن نفر خارج شود، وارث توانایی‌اش را به ارث می‌برد (طبق قوانین میز، معمولاً کارآگاه/زره‌ساز/عطار)." },
  herbalist: { faName: "عطار", teamFa: "شهر", hintFa: "زهر + پادزهر", descFa: "هر شب می‌تواند یک نفر را مسموم کند. صبح گرداننده اعلام می‌کند زهر وارد بازی شده. اگر فرد مسموم تا پایان روز از بازی خارج نشود، رأی‌گیری برای دادن پادزهر انجام می‌شود. دن مافیا یک پادزهر دارد." },
  armorsmith: { faName: "زره‌ساز", teamFa: "شهر", hintFa: "نجاتِ یک‌باره", descFa: "یک‌بار در کل بازی می‌تواند خودش را از شلیک یا حذف نجات دهد." },
  suspect: { faName: "مظنون", teamFa: "شهر", hintFa: "استعلامِ مثبت", descFa: "شهروند است، اما استعلام کارآگاه برای او «مثبت» (مافیا) نشان می‌دهد." },

  // --- Zodiac ---
  alcapone: { faName: "آلکاپن", teamFa: "مافیا", hintFa: "رئیس", descFa: "رئیس مافیاست؛ استعلام کارآگاه برای او همیشه «منفی» (شهروند) است." },
  zodiac: { faName: "زودیاک", teamFa: "مستقل", hintFa: "شلیکِ شب‌های زوج", descFa: "تیم مستقل. فقط در شب‌های زوج می‌تواند شلیک کند و یک نفر را از بازی خارج کند. با شلیک شبانه کشته نمی‌شود؛ فقط با رأی، تفنگ روزانه یا بمب‌گذاری خارج می‌شود. اگر به محافظ شلیک کند، خودش کشته می‌شود." },
  magician: { faName: "شعبده‌باز", teamFa: "مافیا", hintFa: "گرفتن قابلیت", descFa: "هر شب با هماهنگی تیم مافیا یک نفر از شهر را انتخاب می‌کند و توانایی شبانه او را غیرفعال می‌کند." },
  bomber: { faName: "بمب‌گذار", teamFa: "مافیا", hintFa: "بمب‌گذاری", descFa: "یک‌بار در کل بازی می‌تواند بمب‌گذاری کند: یک کد بین ۱ تا ۴ به گرداننده می‌دهد و یک نفر را هدف قرار می‌دهد. هدف باید همان عدد را حدس بزند — درست = زنده / غلط = خارج." },
  guard: { faName: "محافظ", teamFa: "شهر", hintFa: "ضد بمب/زودیاک", descFa: "وقتی بمب‌گذاری اعلام می‌شود، محافظ می‌تواند خودش را فدای هدف کند و کد خنثی‌سازی را حدس بزند: درست = هر دو زنده / غلط = محافظ خارج ولی هدف زنده. اگر زودیاک به محافظ شلیک کند، زودیاک کشته می‌شود.", canSacrificeForBomb: true },
  ocean: { faName: "اوشن", teamFa: "شهر", hintFa: "بیداری شهر", descFa: "دو بار در کل بازی می‌تواند شب چند نفر را بیدار کند تا با چشم باز مشورت کنند. اگر اشتباهاً یک مافیا یا زودیاک را بیدار کند، اوشن از بازی خارج می‌شود." },
  gunslinger: { faName: "تفنگدار", teamFa: "شهر", hintFa: "دادن تفنگ", descFa: "سه تفنگ دارد: ۲ تیر مشقی + ۱ تیر جنگی (خودش نمی‌داند کدام‌ها مشقی‌اند). شب تفنگ‌ها را به بازیکنان می‌دهد؛ گیرنده روز بعد می‌تواند استفاده کند." },

  // --- Representative (نماینده) ---
  don: { faName: "دن مافیا", teamFa: "مافیا", hintFa: "رهبر + رأی خیانت", descFa: "رهبر تیم مافیاست؛ استعلام او همیشه «منفی» (شهروند) است. یک‌بار در هر روز می‌تواند «رأی خیانت» بزند: مخفیانه یک رأی از یک نماینده کم یا به او اضافه می‌کند. اگر خودش نماینده شود، نمی‌تواند این قدرت را روی خودش اعمال کند." },
  rebel: { faName: "یاغی", teamFa: "مافیا", hintFa: "نفر دوم / ترور", descFa: "نفر دوم تیم مافیاست. اگر دن یا هکر از بازی خارج شوند، یاغی به «ترور» تبدیل می‌شود و می‌تواند قبل از رأی‌گیری روزانه یک نفر را حذف کند — محافظ و افراد تحت‌محافظت را نمی‌تواند هدف قرار دهد." },
  hacker: { faName: "هکر", teamFa: "مافیا", hintFa: "مسدودکردن توانایی", descFa: "هر شب توانایی یک بازیکن را مسدود می‌کند؛ آن بازیکن همان شب نمی‌تواند از توانایی خود استفاده کند (مثلاً پزشک نمی‌تواند نجات دهد)." },
  guide: { faName: "راهنما", teamFa: "شهر", hintFa: "استعلام / خطر لو رفتن", descFa: "هر شب یک نفر را انتخاب می‌کند: اگر شهروند باشد مثل کارآگاه استعلام می‌گیرد؛ اگر مافیا باشد آن عضو مافیا بیدار می‌شود و هویت راهنما را می‌شناسد (راهنما لو می‌رود). نمی‌تواند دو شب پشت‌سرهم یک نفر را انتخاب کند." },
  minemaker: { faName: "مین‌گذار", teamFa: "شهر", hintFa: "مین یک‌باره", descFa: "یک‌بار در کل بازی روی یک نفر مین می‌گذارد. اگر مافیا همان شب آن نفر را شات کند، مین منفجر می‌شود و یک داوطلب از تیم مافیا نیز از بازی خارج می‌شود." },
  lawyer: { faName: "وکیل", teamFa: "شهر", hintFa: "مصونیت روز", descFa: "یک‌بار در کل بازی یک نفر را انتخاب می‌کند تا روز بعد از حذف با رأی‌گیری مصون باشد." },
  bodyguard: { faName: "محافظ (سناریو نماینده)", teamFa: "شهر", hintFa: "محافظت از ترور", descFa: "هر شب یک نفر را از ترور یاغی محافظت می‌کند. خودِ محافظ نیز در برابر ترور مصون است." },
  soldier: { faName: "سرباز", teamFa: "شهر", hintFa: "تیر یک‌باره", descFa: "شبانه یک تیر به یکی از بازیکنان می‌دهد. اگر تیر را به مافیا بدهد → سرباز خودش از بازی خارج می‌شود. اگر به شهروند بدهد → آن شهروند در همان شب قابلیت شلیک دارد: شلیک به مافیا (نه دون) → مافیا خارج؛ شلیک به دون مافیا → هیچ‌کس خارج نمی‌شود؛ شلیک به شهروند → خودش خارج می‌شود." },

  // --- Godfather (game) ---
  leon: { faName: "لئون", teamFa: "شهر", hintFa: "حرفه‌ای شهر", descFa: "شب‌ها می‌تواند به کسی شلیک کند. اگر به شهروند شلیک کند، خودش از بازی خارج می‌شود و دکتر نمی‌تواند نجات دهد. یک جلیقه دارد (اولین شلیک مافیا را تحمل می‌کند)." },
  constantine: { faName: "کنستانتین", teamFa: "شهر", hintFa: "بازگردانی", descFa: "یک‌بار در کل بازی می‌تواند یک بازیکنِ اخراج‌شده را به بازی برگرداند — فقط اگر نقش آن بازیکن هنوز توسط گرداننده اعلام نشده باشد." },
  citizenKane: { faName: "همشهری کین", teamFa: "شهر", hintFa: "افشا", descFa: "یک‌بار در کل بازی یک نفر را نشان می‌دهد؛ اگر مافیا باشد، گرداننده روز بعد نقشش را افشا می‌کند (در بازی می‌ماند) و همان شب کین با تیر غیب خارج می‌شود. اگر اشتباه: اتفاقی نمی‌افتد." },
  nostradamus: { faName: "نوستراداموس", teamFa: "مستقل", hintFa: "شب معارفه", descFa: "فقط شب معارفه بیدار می‌شود. ۳ نفر را نشان می‌دهد و گرداننده تعداد مافیاهای داخل آن ۳ را اعلام می‌کند. نوستراداموس بر اساس این اطلاعات ساید خود را انتخاب می‌کند (اگر ۲ نفر از ۳ مافیا باشند، معمولاً مجبور است ساید مافیا را انتخاب کند)." },
};

// English role labels (UI only). If a role isn't present here, it falls back to Persian.
const ROLE_I18N = {
  citizen: { name: "Citizen", hint: "No ability", desc: "No night ability. Help find mafia through discussion and voting." },
  mafia: { name: "Mafia", hint: "No ability", desc: "No standalone ability. Coordinate at night; mislead during the day." },
  mafiaBoss: { name: "Mafia Boss", hint: "Leader + shot", desc: "Mafia leader; decides the final night shot. Always shows as 'citizen' (negative) to the Detective." },
  godfather: { name: "Godfather", hint: "Leader + shot", desc: "Mafia leader; decides the night shot. Always shows as 'citizen' (negative) to the Detective." },
  swindler: { name: "Charlatan", hint: "Disrupts inquiry", desc: "Targets one player each night. If the Detective is targeted, that night's inquiry result is forced 'citizen' regardless of the actual inquiry target. Knows the mafia team but wakes independently." },
  nato: { name: "NATO", hint: "Guess a role", desc: "Once per game, guesses a player's exact role; if correct, that player is eliminated unconditionally. Usually replaces the night shot." },
  negotiator: { name: "Negotiator", hint: "Convert", desc: "When 1–2 mafia are eliminated, may activate a Negotiation Night (no mafia shot). Picks a target: if Simple Citizen or Armored, they join mafia; otherwise negotiation fails." },
  natasha: { name: "Natasha", hint: "Night silence", desc: "Each night silences one player — they cannot speak the following day. Cannot silence the same player on consecutive nights." },
  doctorLecter: { name: "Dr. Lecter", hint: "Save (mafia)", desc: "Mafia doctor. Can save any player from the night shot each night. Self-save: only once per game." },
  jokerMafia: { name: "Mafia Joker", hint: "Flip inquiry", desc: "Max 2 times per game, selects a player to have their Detective inquiry result flipped that night. Cannot target the same player on consecutive nights." },
  matador: { name: "Matador", hint: "Disable ability", desc: "Each night marks one player; that player loses their ability for 24 hours. Cannot choose the same player two consecutive nights." },
  saulGoodman: { name: "Saul Goodman", hint: "Buy/convert", desc: "Once per game can buy a Simple Citizen and convert them to Simple Mafia. The host announces a purchase will occur that night." },

  detective: { name: "Detective", hint: "Night inquiry", desc: "Each night can check one player's side. The host signals the result. Mafia Boss and Godfather always show as 'citizen' (negative)." },
  investigator: { name: "Inspector", hint: "Interrogation", desc: "Once per game can call an interrogation: selects two players who briefly defend themselves; then the whole table votes only between those two." },
  doctor: { name: "Doctor", hint: "Night save", desc: "Can save one player per night from the mafia shot. Cannot save the same person on consecutive nights. Self-save: only once per game." },
  watson: { name: "Dr. Watson", hint: "Save", desc: "Acts like the Doctor: saves one player per night. Self-save: only once per game." },
  researcher: { name: "Researcher", hint: "Link", desc: "Each night (not intro night) can link to a player. If Researcher is eliminated (shot or vote), the linked player is also eliminated — usually the Mafia Boss is excepted." },
  invulnerable: { name: "Invulnerable", hint: "Night armor", desc: "Cannot be killed by the mafia's night shot. Only eliminated via daytime vote or special conditions." },
  armored: { name: "Armored", hint: "Armor + return", desc: "Immune to night shots. If voted out during the day, role is revealed and they return to the game — no longer eligible for negotiation." },
  sniper: { name: "Sniper", hint: "Limited shot", desc: "One shot per game. If shoots a citizen: Sniper is eliminated (Doctor cannot prevent this). If shoots mafia: target is eliminated." },
  professional: { name: "Professional", hint: "Shot", desc: "Can shoot at night. If shoots a citizen by mistake, Professional is eliminated." },
  reporter: { name: "Reporter", hint: "Negotiation inquiry", desc: "In the Negotiator scenario, wakes on Negotiation Night and learns whether the negotiation target was a citizen/armored or not." },
  representative: { name: "Representative", hint: "Day power", desc: "Once per game may use one of two day powers: veto the current vote (cancel it entirely), or protect one player from elimination that day. Wakes at night for host notification only — no night action." },
  hardJohn: { name: "Hard John", hint: "Extra life", desc: "Survives the first mafia night shot (usually unaware it happened). Twice per game may ask the host for the side of any eliminated player." },
  psychologist: { name: "Psychiatrist", hint: "Mute", desc: "Twice per game can remove a player's ability to speak for that session." },
  mayor: { name: "Mayor", hint: "Veto/out", desc: "Once per game (when 2+ players are in defense and Mayor is not one of them) may cancel the vote or directly order one defendant eliminated." },
  seller: { name: "Seller", hint: "Remove ability", desc: "Once per game removes a player's ability for the rest of the game. The host announces the target the following morning." },
  priest: { name: "Priest", hint: "Support talk", desc: "Each night selects players to receive extra speaking time the next day. Can also neutralize Natasha's silence effect." },
  judge: { name: "Judge", hint: "Change vote", desc: "Once per game can void the day vote result, usually declared at night to take effect the following day." },
  commander: { name: "Commander", hint: "Confirm shot", desc: "After the Sniper chooses a target, Commander wakes and can confirm or cancel the shot." },

  danMafia: { name: "Mafia Don", hint: "Leader + antidote", desc: "Mafia leader; always shows 'citizen' to Detective. Has one antidote (against Herbalist poison). May have trading abilities (Capo scenario rules)." },
  witch: { name: "Witch", hint: "Copy ability", desc: "Each night picks a citizen; if that citizen has an ability, it is applied to the Witch instead (e.g., picks Detective → Witch gets an inquiry; picks Herbalist → Witch poisons someone)." },
  executioner: { name: "Executioner", hint: "Guess a role", desc: "Like NATO: if the exact role guess is correct, the target is eliminated unconditionally." },
  informant: { name: "Informant", hint: "Spy", desc: "Mafia spy; shows 'citizen' to Detective. If the Village Elder links them, they respond like a citizen without exposing the Village Elder." },
  kadkhoda: { name: "Village Elder", hint: "City link", desc: "Twice per game can link to a player: that player wakes (without knowing the Village Elder's role). If a citizen or Informant — safe; if a real mafia member — Village Elder is eliminated." },
  heir: { name: "Heir", hint: "Inherit role", desc: "On intro night selects a player to inherit from. Until that player is eliminated, Heir is immortal (immune to night shots). When the target is eliminated, Heir inherits their ability (usually Detective, Armorsmith, or Herbalist)." },
  herbalist: { name: "Herbalist", hint: "Poison + antidote", desc: "Each night can poison one player. Morning: host announces poison is active. If the poisoned player survives the day, a vote decides whether to give the antidote. Don has one antidote." },
  armorsmith: { name: "Armorsmith", hint: "One-time save", desc: "Once per game can save themselves from a shot or elimination." },
  suspect: { name: "Suspect", hint: "Positive inquiry", desc: "A citizen whose Detective inquiry shows 'mafia' (positive)." },

  alcapone: { name: "Al Capone", hint: "Leader", desc: "Mafia leader; always shows 'citizen' (negative) to the Detective." },
  zodiac: { name: "Zodiac", hint: "Even-night shot", desc: "Independent team. Can shoot on even nights only; immune to night shots. Eliminated only by vote, day gun, or bomb. Shooting the Guard causes Zodiac's own death." },
  magician: { name: "Magician", hint: "Disable ability", desc: "Each night (coordinating with mafia) picks a city player and disables their night ability." },
  bomber: { name: "Bomber", hint: "Bomb", desc: "Once per game plants a bomb: gives the host a secret code (1–4) and picks a target. Target must guess the code — correct = survives, wrong = eliminated." },
  guard: { name: "Guard", hint: "Anti-bomb/Zodiac", desc: "When a bomb is announced, may sacrifice to take the target's place and guess the disarm code. Correct = both survive; wrong = Guard eliminated, target survives. Zodiac shooting Guard kills Zodiac." },
  ocean: { name: "Ocean", hint: "Wake citizens", desc: "Twice per game can wake a group of citizens for silent consultation. Accidentally waking a mafia member or Zodiac eliminates Ocean." },
  gunslinger: { name: "Gunslinger", hint: "Give guns", desc: "Has 3 guns: 2 blanks + 1 real (doesn't know which is which). Gives guns at night; recipients may shoot during the next day." },

  leon: { name: "Leon", hint: "City pro", desc: "Can shoot at night. If shoots a citizen, Leon is eliminated — Dr. Watson cannot prevent this. Has one vest (survives the first mafia shot)." },
  constantine: { name: "Constantine", hint: "Revive", desc: "Once per game can revive an eliminated player — only if that player's role has not yet been announced by the host." },
  citizenKane: { name: "Citizen Kane", hint: "Reveal", desc: "Once per game marks a player; if mafia, host reveals their role next day (they remain in game) and Kane is eliminated the following night (invisible bullet). If wrong, nothing happens." },
  nostradamus: { name: "Nostradamus", hint: "Intro night", desc: "Wakes only on the intro night. Marks 3 players; host reveals how many are mafia. Nostradamus chooses their side based on this — if 2 of 3 are mafia, usually must join the mafia side." },

  don: { name: "Don", hint: "Leader + betrayal vote", desc: "Mafia leader; always shows 'citizen' to Detective. Once per day may secretly add or subtract 1 vote from any representative's tally. Cannot use this power on themselves if elected representative." },
  rebel: { name: "Rebel", hint: "2nd-in-command / Assassin", desc: "Second-in-command. If the Don or Hacker is eliminated, becomes the Assassin — may eliminate one player before the daily vote. Cannot target the Bodyguard or protected players." },
  hacker: { name: "Hacker", hint: "Block ability", desc: "Each night blocks one player's ability; that player cannot use their night power that night (e.g., Doctor cannot save)." },
  guide: { name: "Guide", hint: "Inquiry / exposure risk", desc: "Each night selects a player: if citizen, receives an inquiry result (like Detective); if mafia, that mafia member wakes and learns the Guide's identity (Guide is exposed). Cannot target the same player on consecutive nights." },
  minemaker: { name: "Minemaker", hint: "One-time mine", desc: "Once per game plants a mine on one player. If the mafia shoots that same player the same night, the mine activates and a volunteering mafia member is also eliminated." },
  lawyer: { name: "Lawyer", hint: "Day immunity", desc: "Once per game selects a player to be immune from vote-elimination the following day." },
  bodyguard: { name: "Bodyguard", hint: "Protect from assassination", desc: "Each night protects one player from the Rebel's assassination. Bodyguard themselves is also immune to assassination." },
  soldier: { name: "Soldier", hint: "One-time bullet", desc: "At night gives one bullet to a player. If given to mafia → Soldier is eliminated. If given to a citizen → that citizen may shoot: hitting mafia (non-Don) → mafia eliminated; hitting Don → nobody dies; hitting a citizen → recipient is eliminated." },
};
